paths:
  /camionneurs:
    get:
      summary: Récupérer la liste des camionneurs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Camionneur.v1.yaml
              examples: {}
      operationId: get-camionneurs
      tags:
        - camionneurs
        - get
      description: Permet de récupérer la liste de tous les camionneurs
    post:
      summary: Créer un camionneur
      operationId: post-camionneurs
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Camionneur.v1.yaml
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                prenom:
                  type: string
              required:
                - nom
                - prenom
        description: ''
      description: 'Permet de créer un camionneur, il est ensuite renvoyé.'
  /chantiers:
    get:
      summary: Récupérer la liste des chantiers
      tags:
        - chantiers
        - get
      operationId: get-chantiers
      description: Permet de récupérer la liste de tous les chantiers
      requestBody: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Chantiers.v1.json
    post:
      summary: Créer un chantier
      operationId: post-chantiers
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Chantiers.v1.json
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      description: 'Permet de créer un chantier, il est ensuite renvoyé.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                lieuChargementId:
                  type: string
                  description: 'uuid [clé étrangère]'
                lieuDéchargementId:
                  type: string
                  description: 'uuid [clé étrangère]'
              required:
                - nom
                - lieuChargementId
                - lieuDéchargementId
  /etapes:
    get:
      summary: Récupérer la liste des étapes
      tags:
        - etapes
        - get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Etape.v1.json
      operationId: get-etapes
      description: 'Permet de récupérer la liste de toutes les étapes '
    post:
      summary: Commencer une étape
      operationId: post-etapes
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Etape.v1.json
        '400':
          description: Bad Request
          content:
            text/html:
              schema:
                type: string
              examples: {}
        '500':
          description: Internal Server Error
          content:
            text/html:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                dateDébut:
                  type: integer
                  description: timestamp
                type:
                  type: string
                  description: '"chargement", "déchargement"'
                CamionneurId:
                  type: integer
                  description: "id du cammioneur effectuant l'étape"
                ChantierId:
                  type: integer
                  description: "id du chantier pour lequel l'étape est effectué"
              required:
                - dateDébut
                - type
                - CamionneurId
                - ChantierId
        description: ''
      tags:
        - etapes
        - post
      description: "Permet de commencer une étape pour un camionneur et un chantier donné, l'étape créer et ensuite renvoyé."
  /grutiers:
    get:
      summary: Récupérer la liste des grutiers
      tags:
        - grutiers
        - get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Grutier.v1.json
      operationId: get-grutiers
      description: Permet de récupérer la liste de tous les grutiers
    post:
      summary: Créer un grutier
      operationId: post-grutiers
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Grutier.v1.json
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      description: "Permet d'ajouter un grutier à la base de données, le grutier créer et ensuite renvoyé."
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                prenom:
                  type: string
              required:
                - nom
                - prenom
  /lieux:
    get:
      summary: Récupérer la liste des lieux
      tags:
        - 'lieux '
        - get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Lieu.v1.json
      operationId: get-lieux
      description: Permet de récupérer la liste de tous les lieux
    post:
      summary: Créer un lieu
      operationId: post-lieux
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Lieu.v1.json
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      description: 'Permet de créer un lieu, le lieu créé et ensuite renvoyé.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                adresse:
                  type: string
                longitude:
                  type: number
                latitude:
                  type: number
              required:
                - adresse
                - longitude
                - latitude
components:
  schemas: {}
servers:
  - url: 'http://localhost:3000'
info:
  title: SMTP API
  version: 0.0.1
  description: ''
  contact:
    name: Lucas Mas
    email: lucas_mas@msn.com
openapi: 3.0.0
